main_backend/apps/io_ssh/urls.py
from django.urls import path
from django.shortcuts import redirect

from io_ssh.views.IndexView import IndexView
from io_ssh.views.DeviceDetailView import DeviceDetailView
from io_ssh.views.SSHCommandDetailView import SSHCommandDetailView
from io_ssh.views.execute_from_request import execute_command
from io_ssh.views.create_from_request import create_device, create_ssh_command

app_name = "io_ssh"

urlpatterns = [
    path("", IndexView.as_view(), name="v"),
    path("v", lambda x: redirect(f"/")),
    path("device/<int:device_pk>/", DeviceDetailView.as_view(), name="device_detail"),
    path("create_device/", create_device, name="create_device"),
    path(
        "device/<int:pk_device>/create_ssh_command/",
        create_ssh_command,
        name="create_ssh_command",
    ),
    path(
        "device/<int:pk_device>/command/<int:command_pk>/",
        SSHCommandDetailView.as_view(),
        name="command_detail",
    ),
    path(
        "device/<int:pk_device>/command/<int:command_pk>/execute_command/",
        execute_command,
        name="execute_command",
    ),
]

main_backend/apps/polls/urls.py
from django.urls import path

from polls import views

app_name = "polls"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("<int:pk>/results/", views.ResultsView.as_view(), name="results"),
    path("<int:question_id>/vote/", views.vote, name="vote"),
]

main_backend/urls.py
from django.contrib import admin
from django.urls import include, path
from django.shortcuts import redirect

urlpatterns = [
    path("admin/", admin.site.urls),
    # MY APPS
    path("polls/", include("polls.urls")),
    path("", lambda x: redirect(f"io_ssh/")),
    path("io_ssh/", include("io_ssh.urls")),
]

main_backend/apps/io_ssh/models/Device.py
from django.db import models

from io_ssh.models.DeviceType import DeviceType


class Device(models.Model):
    create_date = models.DateTimeField("date created", auto_now_add=True, blank=False)
    name = models.CharField(max_length=50)
    type = models.ForeignKey(DeviceType, on_delete=models.CASCADE, null=True)

    class Meta:
        ordering = ["name"]
        verbose_name_plural = "Devices"
        unique_together = ("name", "type")

main_backend/apps/io_ssh/models/DeviceType.py
from django.db import models


class DeviceType(models.Model):
    model = models.CharField(max_length=255)
    version = models.CharField(max_length=20)
    model_link = models.URLField(max_length=255)
    gpio = models.BooleanField(default=True)

    class Meta:
        ordering = ["model"]
        verbose_name_plural = "Device Types"
        unique_together = ("model", "version", "gpio")

    def __str__(self):
        return f"{self.model} {self.version}"

    def device_type_printer(self):
        return (
            f"[{self.__str__()}] | {'There is ' if self.gpio else 'There is no '}GPIO"
        )

main_backend/apps/io_ssh/models/PortType.py
from django.db import models


class PortType(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        ordering = ["name"]
        verbose_name_plural = "Port Types"

main_backend/apps/io_ssh/models/SSHCommand.py
from django.db import models

from taggit.managers import TaggableManager

from io_ssh.models.Device import Device


class SSHCommand(models.Model):
    command = models.CharField(max_length=500)
    device = models.ForeignKey(Device, on_delete=models.CASCADE)
    tags = TaggableManager()

    @staticmethod
    def get_by_id(id_):
        try:
            return SSHCommand.objects.filter(device_id=id_)
        except SSHCommand.DoesNotExist:
            return []

    def connect_and_execute(self):
        pass

main_backend/apps/io_ssh/models/SshHandler.py
from django.db import models


class SSHHandler(models.Model):
    """
    need a rsa key handler: - generate
                            - export
                            - import
    """

    username = models.CharField(max_length=50, null=False)
    host = models.CharField(max_length=50, null=False)
    port = models.CharField(max_length=4, null=False)
    password = models.CharField(max_length=50, null=False)
    ssh_key = models.TextField(null=False)

main_backend/apps/io_ssh/forms/DeviceForm.py
from django import forms

from io_ssh.models.Device import Device
from io_ssh.models.DeviceType import DeviceType


class DeviceForm(forms.ModelForm):
    name = forms.CharField(label="Device name", max_length=255)
    type = forms.ModelChoiceField(
        label="Device model type",
        required=True,
        queryset=DeviceType.objects.all(),
    )

    class Meta:
        model = Device
        fields = ["name", "type"]

main_backend/apps/io_ssh/forms/NameForm.py
from django import forms


class NameForm(forms.Form):
    your_name = forms.CharField(label="Your name", max_length=100)

main_backend/apps/io_ssh/forms/SSHCommandForm.py
from django import forms

from io_ssh.models.SSHCommand import SSHCommand


class SSHCommandForm(forms.ModelForm):
    command = forms.CharField(label="SSH command")

    class Meta:
        model = SSHCommand
        fields = [
            "command",
        ]

main_backend/apps/io_ssh/views/DeviceDetailView.py
from django.views import generic
from django.shortcuts import get_object_or_404

from io_ssh.models.Device import Device
from io_ssh.models.SSHCommand import SSHCommand


class DeviceDetailView(generic.DetailView):
    model = Device
    template_name = "io_ssh/device_detail.html"

    def get_object(self):
        return get_object_or_404(Device, id=self.kwargs["device_pk"])

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data["ssh_command_list"] = SSHCommand.get_by_id(self.kwargs["device_pk"])
        return data

main_backend/apps/io_ssh/views/IndexView.py
from django.views import generic

from io_ssh.models.Device import Device


class IndexView(generic.ListView):
    template_name = "io_ssh/index.html"
    context_object_name = "latest_device_list"

    @staticmethod
    def get_queryset():
        return Device.objects.order_by("-create_date")[:5]

main_backend/apps/io_ssh/views/SSHCommandDetailView.py
from django.views import generic
from django.shortcuts import get_object_or_404

from io_ssh.models.SSHCommand import SSHCommand


class SSHCommandDetailView(generic.DetailView):
    model = SSHCommand
    template_name = "io_ssh/command_detail.html"

    def get_object(self):
        command = get_object_or_404(SSHCommand, id=self.kwargs["command_pk"])
        return command

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        return data

main_backend/apps/io_ssh/views/create_from_request.py
from django.urls import reverse
from django.shortcuts import render
from django.http import HttpResponseRedirect

from io_ssh.models.Device import Device
from io_ssh.models.SSHCommand import SSHCommand

from io_ssh.forms.DeviceForm import DeviceForm
from io_ssh.forms.SSHCommandForm import SSHCommandForm


def create_device(request):
    if request.method == "POST":
        form = DeviceForm(request.POST)
        if form.is_valid():
            print(form.cleaned_data)
            Device.objects.update_or_create(
                name=form.cleaned_data["name"], type_id=form.cleaned_data["type"].pk
            )
            return HttpResponseRedirect(reverse("io_ssh:v"))
    else:
        form = DeviceForm()
    return render(request, "io_ssh/create_device.html", {"form": form})


def create_ssh_command(request, pk):
    if request.method == "POST":
        form = SSHCommandForm(request.POST)
        if form.is_valid():
            SSHCommand.objects.update_or_create(
                command=form.cleaned_data["command"], device_id=pk
            )
            return HttpResponseRedirect(
                reverse(f"io_ssh:device_detail", kwargs={"pk": pk})
            )
    else:
        form = SSHCommandForm()
    return render(
        request,
        f"io_ssh/create_ssh_command.html",
        {"form": form},
    )

main_backend/apps/io_ssh/views/db_handler.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        return render(
            request,
            "io_ssh/device_detail.html",
            {
                "question": question,
                "error_message": "You didn't select a choice.",
            },
        )
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse("polls:results", args=(question.id,)))

main_backend/apps/io_ssh/views/execute_from_request.py
from django.shortcuts import HttpResponseRedirect, reverse


# create form that execute the specified command
# then return the log
def execute_command(request, device_pk, command_pk):
    print("ici", request, command_pk, device_pk)
    # if (request.GET.get('exec_btn')):
    #     pass # call function
    return HttpResponseRedirect(
        reverse(
            f"io_ssh:execute_command",
            kwargs={"device_pk": device_pk, "command_pk": command_pk},
        )
    )

main_backend/apps/io_ssh/templates/io_ssh/command_detail.html
<!doctype html>
<html>
<head>
    <meta charset="UTF-8">
    <title>DETAIL COMMAND IO_SSH</title>
</head>
<body>
<h1>command.command</h1>
<button type="submit" onclick="href='{% url 'io_ssh:execute_command' device_pk=command.device command_pk=command.pk%}'" name='exec_btn'>
    Execute Command
</button>
</body>
</html>

main_backend/apps/io_ssh/templates/io_ssh/create_device.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>DEVICES IO_SSH</title>
</head>
<body>
<form action="/io_ssh/create_device/" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Create Device">
</form>
</body>
</html>

main_backend/apps/io_ssh/templates/io_ssh/create_ssh_command.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>CREATE SSH COMMAND</title>
</head>
<body>
<form method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Create SSH Command">
</form>
</body>
</html>

main_backend/apps/io_ssh/templates/io_ssh/detail.html
<!doctype html>
<html>
<head>
    <meta charset="UTF-8">
    <title>DETAIL IO_SSH</title>
</head>
<body>
<h1>{{ device.name }} {{ device.type|device_type_printer }}</h1>
{% if ssh_command_list %}
    <ul>
        {% for command in ssh_command_list %}
            <li><a href="{% url 'io_ssh:detail' command.id %}">{{ command.command }}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <p>No SSH command are in '{{ device.name }}' available.</p>
{% endif %}
<a href="{% url 'io_ssh:create_ssh_command' device.id %}">Create a SSH command</a>
</body>
</html>

main_backend/apps/io_ssh/templates/io_ssh/device_detail.html
<!doctype html>
<html>
<head>
    <meta charset="UTF-8">
    <title>DETAIL DEVICE IO_SSH</title>
</head>
<body>
<h1>{{ device.name }} {{ device.type|device_type_printer }}</h1>
{% if ssh_command_list %}
    <ul>
        {% for command in ssh_command_list %}
            <li><a href="{% url 'io_ssh:command_detail' pk_device=device.id pk_command=command.id%}">{{ command.command }}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <p>No SSH command are in '{{ device.name }}' available.</p>
{% endif %}
<a href="{% url 'io_ssh:create_ssh_command' pk_device=device.id %}">Create a SSH command</a>
</body>
</html>

main_backend/apps/io_ssh/templates/io_ssh/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>IO_SSH INDEX</title>
</head>
<body>
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'io_ssh/style.css' %}">
{% if latest_device_list %}
    <ul>
        {% for device in latest_device_list %}
            <li><a href="{% url 'io_ssh:device_detail' device_pk=device.pk %}">{{ device.name }}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <p>No Device are available.</p>
{% endif %}
<a href="{% url 'io_ssh:create_device' %}">Create a device</a>
</body>
</html>